### ISSUE TITLE
Add hostname to the JSON docs

### ISSUE THREAD

**Issue by rtoma** [2ndquadrant-it/redislog#14]
Can you add a 'hostname' or 'host' field to each JSON doc with the hostname of the local machine?

When you send events to Redis, the downstream consuming Logstash instance has no clue what host it originally came from. Making it impossible to filter on events from 1 specific server in Kibana.

**Comment by mnencia** [comment]
At the moment, you can use a different key for each postgres server to allow logstash to distinguish them.

However, I think that what you proposed on #13 is a superset of this one, hence I'm closing this as a duplicate.
